#!/bin/bash
# Simple helper script to exercise unittests using all available
# (under /app/local/usr/bin and /app/local/usr/local/bin python2.*)

set -eu

failed=
for python in /app/local/usr/{,local/}bin/python2.[0-9]{,.*}{,-dbg}
do
	[ -e "$python" ] || continue
	echo "Testing using $python"
	$python ./fail2ban-testcases "$@" || failed+=" $python"
done

if [ ! -z "$failed" ]; then
	echo "E: Failed with $failed"
	exit 1
fi
